name: Release WinIsland plugin

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: WinIslandProject/PluginMarketplace/.github/workflows/build-plugin.yml@196e514380257d773bd3e1e5f386a8d3e3075050
